name: Next.js CI

on:
  push:
    branches:
      - main
      - develop

  pull_request:
    branches:
      - "**"

jobs:
  build-and-lint:
    name: Build and Lint
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.19.2]

    steps:
      - name: ⬇️ Checkout code
        uses: actions/checkout@v4

      - name: 🟢 Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: 📦 Install dependencies
        run: npm ci

      - name: 🧹 Run ESLint
        run: npm run lint

      - name: 🛠️ Build Project
        run: npm run build

      - name: ✅ Run Type Check
        run: npx tsc --noEmit
